---
wordpress:
  image: wordpress
  ports:
    - "80:80"
  links:
    - "mysql"

mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: "aet2NoSh"
  volumes:
    - "wordpress_data:/var/lib/mysql"
